name: Update Wiki

on:
  push:
    paths:
      - "_wiki/**"  # Trigger only when _wiki directory changes
    branches:
      - master  # And only on the master branch

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use the latest version that supports Node.js 20
        
      - name: Debug - List Files
        run: ls -R

      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        env:
          # We use rsync
          # WIKI_DIR's default is wiki/
          WIKI_DIR: _wiki/  # Ensure this ends with a /
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.OWNER_EMAIL }}
          GH_NAME: ${{ github.actor }}
